#!/bin/bash -l

#SBATCH -N 1
#SBATCH -J generate_dataset
#SBATCH -o /cosma/home/durham/dc-amvr1/GitHub/utils/cosma/output_%A.out
#SBATCH -e /cosma/home/durham/dc-amvr1/GitHub/utils/cosma/error_%A.err
#SBATCH -p cosma7
#SBATCH -A dp004
#SBATCH -t 72:00:00
#SBATCH --mail-type=END
#SBATCH --mail-user=aristeidis.amvrosiadis@durham.ac.uk

module purge
module load python/3.6.5
module load intel_comp/2018
module load openmpi/3.0.1
module load fftw/3.3.7

source $HOME/autolens_envs/autolens_0.45.0_modified/bin/activate

python3 /cosma/home/durham/dc-amvr1/GitHub/utils/cosma/test_sbatch.py "$arg0" "$arg1" "$arg2" "$arg3"
